/**
 * DO NOT EDIT THIS FILE!
 *
 * This file contains the server for the exercise 5.5
 * Grader will not use this file and your changes to this file are not used
 * in the grading process. All your code should go into the file "messages-as-json.js"
 */

const http = require('http');
const users = require('./users.json'); // NOTE: node can load and parse json directly
const PORT = 3000;

http
  .createServer((request, response) => {
    // Set response headers
    response.writeHead(200, {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*'
    });

    // Write the JSON data into the response body.
    // NOTE: The body must always be text and therefore JSON.stringify() is needed.
    response.write(JSON.stringify(users));
    response.end();
  })
  .listen(PORT, () => console.log(`Server listening on port ${PORT}...`));